### PR TITLE
Update to `google-closure-compiler@20240317.0.0`

### LINKED ISSUE #97: `jschardet.min.js` cannot be loaded into `vm` in node.js
See this code:

```js
const vm = require('vm');
const mod = require('module');
const fs = require('fs');

const content = fs.readFileSync('<path to>/jschardet.min.js', 'utf8');
const scriptSource = mod.wrap(content.replace(/^#!.*/, ''));
const script = new vm.Script(scriptSource);
const compileWrapper = script.runInThisContext({
    filename: 'jschardet.js',
    displayErrors: true
});

console.log(compileWrapper.apply(globalThis, []));
```

When you run it with node.js 20.x:

```
TypeError: Cannot read properties of undefined (reading 'iterator')
    at $jscomp.initSymbolIterator (evalmachine.<anonymous>:1:384)
    at $jscomp.makeIterator (evalmachine.<anonymous>:2:42)
    at evalmachine.<anonymous>:164:334
    at new c (evalmachine.<anonymous>:164:465)
    at evalmachine.<anonymous>:662:132
    at 42../constants (evalmachine.<anonymous>:662:395)
    at f (evalmachine.<anonymous>:5:32)
    at evalmachine.<anonymous>:5:66
    at 19../logger (evalmachine.<anonymous>:390:112)
    at f (evalmachine.<anonymous>:5:32)
```

Fix is in https://github.com/aadsm/jschardet/pull/96

### PR DESCRIPTION
**Pull request by bpasero**
fix https://github.com/aadsm/jschardet/issues/97

👋 We (VS Code) are in the process of moving to ESM (https://github.com/microsoft/vscode/pull/166033) and are running into an issue when loading `jschardet.min.js` into our node.js environment. The error was no longer reproducible when moving to a newer version of `google-closure-compiler`, in fact even just the next version [`v20151216`](https://github.com/google/closure-compiler/wiki/Releases#december-16-2015-v20151216) fixes it. 

The error we see is when attempting to load `jschardet.min.js` with a custom loader we implement to bridge between ESM and CommonJS/AMD. The error is:

```
TypeError: Cannot read properties of undefined (reading 'iterator')
      at $jscomp.initSymbolIterator (evalmachine.<anonymous>:1:384)
      at $jscomp.makeIterator (evalmachine.<anonymous>:2:42)
      at evalmachine.<anonymous>:164:334
      at new c (evalmachine.<anonymous>:164:465)
      at evalmachine.<anonymous>:662:132
      at 42../constants (evalmachine.<anonymous>:662:395)
```

There is more context in https://github.com/microsoft/vscode/issues/160416#issuecomment-2211276269 and onward. 

I think with newer versions of `google-closure-compiler` some polyfills are no longer applied that maybe lead to this issue 🤔 

Curious why this project has never updated this dependency to a later version. With this PR the latest version is picked and obviously the change in `jschardet.min.js` is rather large. Is there a way to validate this works in all environments?

### CODE REVIEW

**Comment by bpasero** [comment]
I was able to distill a minimal repro in https://github.com/aadsm/jschardet/issues/97

**Comment by bpasero** [comment]
@aadsm friendly ping 👋

**Comment by aadsm** [comment]
Oh wow, I really missed this issue, thanks for pinging.
I was actually working on this sometime ago but then other things came up.

**Comment by aadsm** [comment]
It is now available as `jschardet@3.1.4`.

**Comment by bpasero** [comment]
Thanks a bunch!

**Pull request merged**
